name: Publish to NPM Registry
on:
  release:
  workflow_run:
    workflows: ["Create a New Release"]
    types: [completed]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event.name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to different Branch
        uses: actions/checkout@v2
      - name: Setup Node Server
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          yarn install
          yarn build
          npm publish --access public
