name: Create a New Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to different Branch
        uses: actions/checkout@v2
      - name: Read package.json
        id: package-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Show version number
        run: echo "${{ steps.package-version.outputs.prop }}"
