name: Create a New Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to different Branch
        uses: actions/checkout@v2
      - name: Read package.json
        id: package-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Release new version
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.package-version.outputs.prop }}
          name: v${{ steps.package-version.outputs.prop }}
          body: This is a release for v${{ steps.package-version.outputs.prop }}. Ready to use.
          prerelease: false
